services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PORT
        value: 10000
    plan: free
